### ISSUE TITLE
Issues after updating 

### ISSUE THREAD

**Issue by JDL747** [VadimDez/ng2-pdf-viewer#150]
Hi,

I'm getting the following errors after updating to v1.2.3 : 

<img width="438" alt="screen shot 2017-09-03 at 14 47 54" src="https://user-images.githubusercontent.com/3844254/30002993-72baf4e8-90b7-11e7-9e0c-0f90c287a7b4.png">

Thanks for your help

**Comment by RichardBosworth** [comment]
Yep me too

**Comment by vincent-cm** [comment]
Same here I use webpack for env setting.
Issue throw before/at start bootstrapping angular app so no dom rendered.

**Comment by VadimDez** [comment]
Fixed in 1.2.4

**Comment by JDL747** [comment]
Thanks @VadimDez but unfortunately, I'm still having the same error !

I've tried using different version of pdfjs-dist but no luck !

**Comment by VadimDez** [comment]
Fixed in 1.2.5
