### ISSUE TITLE
ng2-pdf not rendering all pages

### ISSUE THREAD

**Issue by hariomdebut** [VadimDez/ng2-pdf-viewer#471]
I am getting a byteArray from back-end and passing it to [src]. it is rendering all pages except last pages. The rendering process is taking too much time. There is a loader rotating at the last page. size of pdf is 17mb and there are 6 pages. I am able to view 5 pages but on 6th page there is a loader.
```html
<pdf-viewer [src]="pdfSrc" [render-text]="false" style="display: block;" [show-all]="true" [autoresize]="true" [original-size]="false" (page-rendered)="pageRendered($event)"></pdf-viewer>
```

```typescript
pageRendered(e: CustomEvent) {
    console.log('(page-rendered)', e); //not getting console for last page only
  }

this.Service
      .processMergeForm(submission)
      .pipe(takeUntil(this.onDestroy$)) 
      .subscribe((data: any) => {
        this.pdfSrc = new Uint8Array(data.byteArray);
        
      }, (error) => {
        console.log('err', error);
      });
```
Here is the response from backend:
```
"data": {
        "byteArray": [
            "0x25", "0x50", "0x44", "0x46", "0x2d", "0x31", "0x2e", "0x36",  "0x0d" ... 16783]
 ```

**Comment by hariomdebut** [comment]
Any suggestion??

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by AlexCorona55** [comment]
I still have the problem, any sugestions?
This is my implementation of pdf-viewer:

`<pdf-viewer #pdfViewer [src]="pdfSrc" [render-text]="true" [render-text-mode]="2" [fit-to-page]="false"
                    [show-all]="true" [original-size]="true" [autoresize]="false" [stick-to-page]="true" [(page)]="page"
                    style="position: relative;font-size: 0.5rem;" (after-load-complete)="loadComplete($event)" (page-rendered)="pageRendered($event)">
                </pdf-viewer>`

**Comment by nbaua** [comment]
> Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

It still is not fixed, I am on version 6.3.2.
It renders only half of the total pages. For example I have a document of 9 pages it only renders the last 5 pages, I have checked the pattern, it starts rendering mid-way or renders only half of them.

**Comment by BL-ShubhamNavale** [comment]
is the issue solved i am still getting the issues first 3 pages are not shown

**Comment by nifaullah** [comment]
The issue mentioned [here ](https://github.com/VadimDez/ng2-pdf-viewer/issues/471#issuecomment-706883381) is not fixed yet. 

It still only renders half the pages, which means if I want to view page 3 on load o

@nbaua were you able to find a solution for this ?

**Comment by navneerajmishra** [comment]
Hi! I'm using version 9.1.5. Only first 2 out of 9 pages render. Other pages are blank. Issue occurs when [show-all] is set to true.

**Comment by sumin27** [comment]
Is this issue closed on versions after 7.0.0? I am still facing this issue where the first 2 pages load and then other pages keep on loading. [show-all] is set to true.
