### ISSUE TITLE
Support on IE & Edge

### ISSUE THREAD

**Issue by brokuto** [VadimDez/ng2-pdf-viewer#478]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ x ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hi 
I noticed, that your PDF is not properly displayed on the Broswers IE and Edge.

Here are some Screenshots
IE11:
[IE first page](https://ibb.co/jwkDZy8)
[IE second Page](https://ibb.co/YBtq6S8)

Edge:
[Edge first Page](https://ibb.co/fCP8p29)
[Edge second Page](https://ibb.co/hKgW8PG)

Is this a problem on my side?

**Comment by celloman** [comment]
I can report that we are seeing this same behavior in IE11 with ng2-pdf-viewer 5.2.3. First page renders fine, subsequent pages render improperly (seem to be mostly blank, with some outlines like the examples above). No console errors, any insight/advice would be helpful.

**Comment by brianmarting** [comment]
Also having the issue, only solution for now would be to show all pages..

**Comment by celloman** [comment]
Interestingly, I just reverted back to the version we had previously used (5.1.2) and this problem seems to have resolved itself...

**Comment by brokuto** [comment]
> 
> 
> Interestingly, I just reverted back to the version we had previously used (5.1.2) and this problem seems to have resolved itself...

Thank you so much this worked for me as well!
And finally someone replied to my issue we've been waiting for almost a month now.... and no one seemed to care helping. (Y)

**Comment by celloman** [comment]
Darn Internet Explorer, lol. I wonder if we should actually keep this issue open so the underlying problem can be fixed in newer versions of this package. We originally upgraded versions because this older version throws some warning about a zlib dependency, so it would be nice to be able to upgrade at some point.

**Comment by brianmarting** [comment]
Agree, we shouldn't close this issue. Downgrading should **not** be a solution...

**Comment by brokuto** [comment]
Alright, yes i reopened the issue but I doubt someone will care about this issue since IE and Edge are not commonly used anymore.

Or in my opinion shouldn't be used that much anymore. But it's still the default browser of my company so we need the support.

I even know what the problem or rather difference is from the version 5.1.2. and the newer one. In the older version all pages are loaded individually instead of only once when you visit the page.

**Comment by arslanahmed9** [comment]
Document with graphics/table is getting corrupted in IE/Edge.
Version: 5.2.4

1- Playback a file which have some graphics/tables in it in IE/EDGE.
2- You will see that it is getting corrupted(See Image) or the table is blank. This ONLY happens in IE/EGDE and works fine in CHROME/FIREFOX

Weird behavior is that if the user clicks  zoom/rotate button on the corrupted page the content begins to display correctly. This seems to be a problem in rendering of file.


![IE-EDGE ng2-pdf-viewer](https://user-images.githubusercontent.com/15634421/60811383-90f40680-a1a8-11e9-924f-9554fffe37ab.png)

**Comment by mamichels** [comment]
Can also report this behavior for IE 11.2608.14393.0 11.095. Still working fine on Chrome. Changing the zoom level will rerender the page correctly.

**Comment by arslanahmed9** [comment]
**I revert back to the version (5.1.2) and the problem still same**

document which I upload

[DocWithGraphics.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/3385559/DocWithGraphics.pdf)


> Interestingly, I just reverted back to the version we had previously used (5.1.2) and this problem seems to have resolved itself...

**Comment by asadmalik3** [comment]
Degra

> Interestingly, I just reverted back to the version we had previously used (5.1.2) and this problem seems to have resolved itself...

Reverting back to 5.1.2 works, but internal PDF navigation stop working in older version.

**Comment by faraz2116** [comment]
> **I revert back to the version (5.1.2) and the problem still same**
> 
> document which I upload
> 
> [DocWithGraphics.pdf](https://github.com/VadimDez/ng2-pdf-viewer/files/3385559/DocWithGraphics.pdf)
> 
> > Interestingly, I just reverted back to the version we had previously used (5.1.2) and this problem seems to have resolved itself...

Also having the same issue can anyone please help

**Comment by SeijiV13** [comment]
Hi any updates on IE11 compatibility? I think reverting the version doesn't still solve the issue

**Comment by brokuto** [comment]
> 
> 
> Any updates on IE11 compatibility? I think reverting the version doesn't still solve the issue

Sadly not... I am very disappointed no one does anything to resolve this issue, because some people in my company still use IE and we need this package.

**Comment by faraz2116** [comment]
reverting the version does solve the problem even the external link is also
not clickable by setting the external-traget as blank

**Comment by mamichels** [comment]
@brokuto If your company heavily depend on the use of this package why dont you go ahead and do a favor for the community and fix the issue?

**Comment by brokuto** [comment]
> 
> 
> @brokuto If your company heavily depend on the use of this package why dont you go ahead and do a favor for the community and fix the issue?

Sorry, because I can't. I don't know how to because I'm not that experienced and I am not the only one with this issue so.... Also, your comment sounds a bit harsh, don't you think? I hope I am just misinterpreting this.

**Comment by PurHur** [comment]
It should sound harsch. People mistake github issues as todo task for the developers. This is rude.

**Comment by VadimDez** [comment]
I do not have a possibility to test IE or Edge, so if anyone could overtake this part - that would be great!

**Comment by seopei** [comment]
I just tested the demo page on IE11.0.9600.18860 and Edge 44.18362.1.0 but I did not see any problems. 
BTW If somebody wants to test with IE or Edge, you can download a free virtual machine with different MS browser versions here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
For Edge you can also use the free account of Browserstack (https://www.browserstack.com/test-on-microsoft-edge-browser#).

**Comment by brokuto** [comment]
> 
> 
> It should sound harsch. People mistake github issues as todo task list for the developers. This is rude.

Geez, you people are so rude all the time. I reopened the Issue because someone begged me to let it be open. Why are you all mad at me? What did I do wrong? This is kind of unfair of you... I just opened the issue because I am inexperienced and I needed help. I am so sorry that I'm not meeting all of your expectations...

**Comment by davir85** [comment]
I have the same issue with Edge & IE. Any news?

> Document with graphics/table is getting corrupted in IE/Edge.
> Version: 5.2.4
> 
> 1- Playback a file which have some graphics/tables in it in IE/EDGE.
> 2- You will see that it is getting corrupted(See Image) or the table is blank. This ONLY happens in IE/EGDE and works fine in CHROME/FIREFOX
> 
> Weird behavior is that if the user clicks zoom/rotate button on the corrupted page the content begins to display correctly. This seems to be a problem in rendering of file.
> 
> ![IE-EDGE ng2-pdf-viewer](https://user-images.githubusercontent.com/15634421/60812234-7a4eaf00-a1aa-11e9-9384-153dc7c4f661.png)

**Comment by seopei** [comment]
@davir85 which file are you using? and what version of the browsers?

**Comment by davir85** [comment]
EDGE version:
- Microsoft Edge 44.18362.267.0
- Microsoft EdgeHTML 18.18362

**ng2-pdf-viewer** version 5.3.4

I can't show you the file because it's from a customer, but sometimes, after loading the PDF on EDGE, the result is the following:
![badVisualization](https://user-images.githubusercontent.com/3436620/64261868-81d1d080-cf2d-11e9-8137-644aecaff7d7.png)

Sometimes the result is correct:
![goodVisualization](https://user-images.githubusercontent.com/3436620/64261950-a4fc8000-cf2d-11e9-8007-6e7eb053f187.png)

**Comment by seopei** [comment]
@davir85 and the version of IE, or is on IE everything ok?
It would be nice the get a file which is not rendering correctly. Could you create one in order that someone can reproduce the bug?
You also could fork this repo and only downgrade the version of pdf.js in the package.json because I thing this bug is not really related to this project. Instead you could have a look into the bugs of pdf.js - maybe there is something that will help to save the bug.

**Comment by ricksmt** [comment]
This section seems to summarize the current PDF library situation: https://www.npmjs.com/package/ngx-extended-pdf-viewer#alternatives

It does seem pdf.js is dropping support for IE/Edge: https://github.com/mozilla/pdf.js/issues/11211

For IE support, the summary suggests either:
- https://www.npmjs.com/package/ngx-extended-pdf-viewer
- https://www.npmjs.com/package/ng2-pdfjs-viewer

**Comment by Gromov-Roman** [comment]
Hello! @VadimDez will this issue be solved?

**Comment by davir85** [comment]
> Hello! @VadimDez will this issue be solved?

Yes, it seems so! Thanks!

**Comment by sup3rcow** [comment]
Hi.

If i set, [show-all]="true", than pdf text is rendered fine in IE.

Maybe it is a problem in line 334.
"New form of page changing"
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/pdf-viewer/pdf-viewer.component.ts

**Comment by KasunGamage** [comment]
any update on this?

**Comment by fireWinters** [comment]
dear brokuto，what you said is not real.Because in China many companies are still using Internet Explorer11。Therefore, I hope your team can still maintain the support for Internet Explorer, thank you very much

**Comment by jpike88** [comment]
This library needs to have in big, bold letter at the top of its README.md

'DOES NOT WORK ON IE11 AND NON-CHROMIUM BASED EDGE'.

I don't like IE11 but it's still used in the MAJORITY of serious enterprises and companies. This library is useless for enterprise use without that support.

Maintainer, please make it clear about compatibility because we wasted a bunch of time integrating this before realizing and looking in the issues.

**Comment by MohamedSahir** [comment]
faced same issue in  angular 9 -  [https://github.com/VadimDez/ng2-pdf-viewer/issues/647](url)

**Comment by mamichels** [comment]
@jpike88 
![image](https://user-images.githubusercontent.com/48212402/90478037-c0579f80-e12c-11ea-9be1-d9bfe022f4a4.png)

**Comment by jpike88** [comment]
@mamichels that's cute. But I have spent hundreds of hours contributing to OSS projects myself. It doesn't mean my work is immune from criticism. 

I've moved to a different library that acknowledges the existence of IE11/Edge anyway.

**Comment by MohamedSahir** [comment]
@mamichels  the library doesn't support ie also not a problem  Edge Browser is a modern browser used everywhere mainly in an organization. even angular supports the modern browser, the library should support that, I have plan move out from this library.
Did you recommend any other library have well support for Edge.

**Comment by pradeepmu-kore** [comment]
How to support ng2 pdf viwer in IE browser & edge. Can anyone tell me

**Im using versions:**
Angular 7.1.3
ng2-pdf-viewer 5.2.3
pdf-dist

Using above libs to generate pdf viewer & In chrome, firefox no issue. Please let me know if anyone solved this issue. Thanks in advance

**Comment by fireWinters** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Use PDF. Js instead of NG2 PDF. PDF. Js has handling for Internet Explorer compatibility.The front-end technology stack we use is Vue, not Angular, and I'm sorry that won't help you.Use the lower version of PDF.js
        
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1987567948
                            
                    
                        
                            
                                    1987567948@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 10/27/2020 20:07，pradeepmu-kore<notifications@github.com> wrote： 



How to support ng2 pdf viwer in IE browser & edge. Can anyone tell me
Im using versions:
Angular 7.1.3
ng2-pdf-viewer 5.2.3
pdf-dist
Using above libs to generate pdf viewer & In chrome, firefox no issue. Please let me know if anyone solved this issue. Thanks in advance

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aivoric** [comment]
We also have the same problem. We are trying to use this library but unfortunately 30% of our users are on IE because they work in older companies which use IE.

Any planned fixes for this?

**Comment by softoika** [comment]
Since version 2.4.456 of PDF.js, es5 compatibility is no longer supported by default [[1]](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsers-are-supported).
To support IE and Edge, it is necessary to use es5 compatible prebuilt. To use es5 compatible prebuilt, the following module paths should be `pdfjs-dist/es5/*` (See https://github.com/mozilla/pdfjs-dist).
https://github.com/VadimDez/ng2-pdf-viewer/blob/4958a535164eb5fbb320cfb17790a1b5dede87dc/src/app/pdf-viewer/pdf-viewer.component.ts#L37-L38
But this fix is not enough because the default CDN worker is not es5 compatible.
https://github.com/VadimDez/ng2-pdf-viewer/blob/4958a535164eb5fbb320cfb17790a1b5dede87dc/src/app/pdf-viewer/pdf-viewer.component.ts#L249-L251

If this library doesn't officially support IE and Edge, I think it should raise the major version based on SemVer.

**Comment by ewelinaolejnik** [comment]
ES5 prebuilt of pdf.worker.js in version 2.4.456 can be found [here](https://www.jsdelivr.com/package/npm/pdfjs-dist?path=es5%2Fbuild&version=2.4.456). It hasn't minified version, but I haven't found any performance issue with this one.
The solution to run the ng2-pdf-viewer on IE and Edge is [here](https://github.com/VadimDez/ng2-pdf-viewer/pull/688/files).

**Comment by pradeepmu-kore** [comment]
> ES5 prebuilt of pdf.worker.js in version 2.4.456 can be found [here](https://www.jsdelivr.com/package/npm/pdfjs-dist?path=es5%2Fbuild&version=2.4.456). It hasn't minified version.
> The solution to run the ng2-pdf-viewer on IE and Edge is [here](https://github.com/VadimDez/ng2-pdf-viewer/pull/688/files).

Thanks for responding. I have to check with pdf es5 modules

**Comment by VadimDez** [comment]
Should be working now with version [6.4.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.0)

**Comment by raccoondev85** [comment]
@VadimDez 
with version 6.4.1 the problem still exists on IE
your demo(https://vadimdez.github.io/ng2-pdf-viewer/) site is also not rendered after second pages as well with IE11
