### ISSUE TITLE
Memory leak issue in IOS when open large PDF file

### ISSUE THREAD

**Issue by wasimbakali** [VadimDez/ng2-pdf-viewer#516]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [] Documentation issue or request
```

Hi There,

I am trying to open large PDF in my ionic 3 angular 5 project its working fine in browser but in IOS when **i try to open large PDF (more than 100 MB)** it gets open but after few seconds screen gets white and app gets refresh.

I found below log just before screen gets white.

> [ProcessSuspension]  0x1c5c710c0 - ProcessAssertion() Unable to acquire assertion for process with PID 0

 
also i googled this error and found that this can be happen when app try to occupy much memory.

Is there any way to open large file without memory leak ?

Thanks in advance!

**Comment by VadimDez** [comment]
Fixed in `6.0.0` See https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#600

**Comment by gamalshaaban1986** [comment]
i am still having the same problem in IOS even after upgrading library, can any one help please

**Comment by VadimDez** [comment]
@gamalshaaban1986 Have you also done this? https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#breaking-change

**Comment by gamalshaaban1986** [comment]
yes , unfortunately the same problem, i think memory is not freed . the scenario i am facing is when trying to open files consequently, it works fine with the first one , then crashes on the next .is there any way to force freeing resources allocated in memory?

**Comment by VadimDez** [comment]
@gamalshaaban1986 before I'll dig into this problem you can try to hide and then show the component - this hack might help for now...

**Comment by gamalshaaban1986** [comment]
Actually i didn't get your point,

my html for your reference

<pdf-viewer [src]="pdfSrc"   style="display: block;" [zoom]="pdfZoom" [rotation]="rotation"
         [original-size]="false" [show-all] ="false" [page]="page"
         (after-load-complete)="afterLoadComplete($event)" ></pdf-viewer>

**Comment by gamalshaaban1986** [comment]
did you mean adding *ngIf="isShown"?

**Comment by VadimDez** [comment]
Could you try the latest version `6.0.1`? Also don't forget about breaking change. pdf-viewer container now should be scrollable for the best performance. https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#breaking-change

**Comment by gamalshaaban1986** [comment]
Thank VadimDez, 
I had tried but for sorry the same memory leak exists

**Comment by htruong24** [comment]
I got the same issue, do we have any temporary solution?

**Comment by VadimDez** [comment]
@htruong24  You could try to do what it says [here](https://github.com/VadimDez/ng2-pdf-viewer/blob/master/CHANGELOG.md#breaking-change) and make the pdf container scrollable, so that it doesn't render all the pages.

**Comment by seopei** [comment]
I have the same issue. I am using Ionic 5 and the latest version of ng2-pdf-viewer. I made the pdf container scrollable.

**Comment by gigallo** [comment]
Hi

We have the same problem using version 7.0.1 and viewing a file of less then 1MB. Any help?

Thanks
