### ISSUE TITLE
Module x has no exported member 'PDFDocumentProxy' +n

### ISSUE THREAD

**Issue by Mibeon** [VadimDez/ng2-pdf-viewer#717]
##### Bug Report or Feature Request (mark with an `x`)

Hello guys.

There's some trouble with this package.

I use following angular specs:
Fresh installation of Angular and only added **ng2-pdf-viewer**

```
    "@angular/animations": "~11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "ng2-pdf-viewer": "^6.3.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
```

I registered the PdfViewerModule in app.module.ts.
Nothing else done. No deps, no tricky relations. Clean angular + import of PdfViewerModule

Running **ng serve**

AND GET THIS

```
Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
           ~~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:28 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
                             ~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:39 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
                                        ~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:1:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.

1 import { PDFJSStatic } from 'pdfjs-dist';
           ~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
           ~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:100 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPromise'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                                                                     ~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:23 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                        ~~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:41 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFViewerParams'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                          ~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:58 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPageProxy'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                           ~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:72 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                                         ~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:83 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
```

To reproduce this just:
- Install fresh angular project
- Add ng2-pdf-viewer
- Import that module in app.module.ts or wherever you need it
- Get the error

In **node_modules** there is @types/pdfjs-dist BUT ng2-pdf-viewer doesn't use it.

I tried to reinstall, to install @types/pdfjs-dist @types/node and rolled back to lower node version. Nothing helps.
I am very hard relied on that package for coming rollout these days.

Can anyone good guy help to fix this?

Shake your hands, dudes.

**Comment by DhyeyMoliya** [comment]
I also have the same error

**Comment by Mibeon** [comment]
> I also have the same error

Look at this answer from this guy. It worked for me for a moment.
[https://github.com/VadimDez/ng2-pdf-viewer/issues/715#issuecomment-767485322](https://github.com/VadimDez/ng2-pdf-viewer/issues/715#issuecomment-767485322)

**Comment by PepijnDhollander** [comment]
I Hope someone fixes it

**Comment by Rahul-kalsha** [comment]
> I also have the same error

I hope it works for you.
[#715] (https://github.com/VadimDez/ng2-pdf-viewer/issues/715#issuecomment-768842630)

**Comment by yogigrantz** [comment]
I get the same error also. Could someone fix this issue please?

**Comment by nsiddiqui25** [comment]
Exact same issue here

**Comment by bobodonia** [comment]
same error here

**Comment by skal1ozz** [comment]
same issue here

**Comment by narendrasinghrathore** [comment]
same issue.

**Comment by narendrasinghrathore** [comment]
cc: @VadimDez

**Comment by MatthieuDye** [comment]
Hey, if by any chance you look this message
Looks like the problem comes with ng2-pdf-viewer's dependency pdfjs-dist which is declared at "latest"
But the lastest version of pdfjs-dist is linked to those problems
The solution is to declare a new version of this package :
`"ng2-pdf-viewer": "~6.3.2",
"pdfjs-dist": "~2.5.207",`

**Comment by narendrasinghrathore** [comment]
@MatthieuDye still same
```
 "ng2-pdf-viewer": "~6.3.2",
    "pdfjs-dist": "~2.5.207",

**Comment by julianfrancodev** [comment]
Same iusse

`    "ng2-pdf-viewer": "^6.3.2",
    "pdfjs-dist": "^2.6.347",
`

**Comment by LAlves91** [comment]
Hi everyone!

I believe the problem is: this library uses @types/pdfjs-dist, which is based on pdfjs-dist 2.1. The problem is, since version v2.6.347, [pdfjs-dist is releasing its own type definitions](https://github.com/mozilla/pdf.js/releases/tag/v2.6.347), which are kind of different from the old ones.

For now, I think the workaround is to fix pdfjs-dist version in our package.json files ("pdfjs-dist": "2.5.207"), so npm won't even try to deviate from this version.

**Comment by narendrasinghrathore** [comment]
> Hi everyone!
> 
> I believe the problem is: this library uses @types/pdfjs-dist, which is based on pdfjs-dist 2.1. The problem is, since version v2.6.347, [pdfjs-dist is releasing its own type definitions](https://github.com/mozilla/pdf.js/releases/tag/v2.6.347), which are kind of different from the old ones.
> 
> For now, I think the workaround is to fix pdfjs-dist version in our package.json files ("pdfjs-dist": "2.5.207"), so npm won't even try to deviate from this version.

And which version of ng2-pdf-viewer, if you can advise?
@LAlves91

**Comment by LAlves91** [comment]
@narendrasinghrathore, I believe as long as you 'freeze' pdfjs-dist in your own project, any version of ng2-pdf-viewer should work. I'd also advise to fix pdfjs-dist in the version ng2-pdf-viewer declares (if your version of ng2-pdf-viewer declares pdfjs-dist@^2.4.456, fix it at this version), just in case!

**Comment by narendrasinghrathore** [comment]
@LAlves91 
I did , but no luck. Deleted node_modules and reinstalled but no success

"ng2-pdf-viewer": "~6.3.2",
"pdfjs-dist": "~2.5.207",

**Comment by LAlves91** [comment]
Can you show the stacktrace?

**Comment by LAlves91** [comment]
@narendrasinghrathore can you check inside your node_modules or in your package-lock.json, to confirm the installed pdfjs-dist version?

**Comment by Owned333** [comment]
Using "@types/pdfjs-dist": "^2.0.1" seems to solving the issue for me...

**Comment by tiagogiroto** [comment]
I have the same problem at describe in the issue, but an error has occurred in build of project, any idea of the solution ?

ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.
#15 45.86
#15 45.86 5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
#15 45.86            ~~~~~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:28 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.     
#15 45.86
#15 45.86 5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
#15 45.86                              ~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:39 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.
#15 45.86
#15 45.86 5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
#15 45.86                                         ~~~~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:1:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.      
#15 45.86
#15 45.86 1 import { PDFJSStatic } from 'pdfjs-dist';
#15 45.86            ~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.      
#15 45.86
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86            ~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:23 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'. 
#15 45.86
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86                         ~~~~~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:41 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFViewerParams'.  
#15 45.86
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86                                           ~~~~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:58 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPageProxy'.     
#15 45.86
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86                                                            ~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:72 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.        
#15 45.86 
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86                                                                          ~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:83 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.  
#15 45.86
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
#15 45.86                                                                                     ~~~~~~~~~~~~~~~
#15 45.86 node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:100 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPromise'.
#15 45.86 
#15 45.86 7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';

**Comment by voegeli** [comment]
I have a working solution with:

-     "ng2-pdf-viewer": "~5.3.4"
-     "pdfjs-dist": "~2.5.207"

Don't use @types/pdfjs-dist

Took me ours, to figure that your.

**Comment by labforcode** [comment]
> 
> 
> I have a working solution with:
> 
>     * ```
>       "ng2-pdf-viewer": "~5.3.4"
>       ```
> 
>     * ```
>       "pdfjs-dist": "~2.5.207"
>       ```
> 
> 
> Don't use @types/pdfjs-dist
> 
> Took me ours, to figure that your.


What is your version of Angular?

**Comment by voegeli** [comment]
> > I have a working solution with:
> > ```
> > * ```
> >   "ng2-pdf-viewer": "~5.3.4"
> >   ```
> > 
> > * ```
> >   "pdfjs-dist": "~2.5.207"
> >   ```
> > ```
> > 
> > 
> > Don't use @types/pdfjs-dist
> > Took me ours, to figure that your.
> 
> What is your version of Angular?

Is working with Angular Version 10 & 11

**Comment by tiagogiroto** [comment]
> I have a working solution with:
> 
> * ```
>   "ng2-pdf-viewer": "~5.3.4"
>   ```
> * ```
>   "pdfjs-dist": "~2.5.207"
>   ```
> 
> Don't use @types/pdfjs-dist
> 
> Took me ours, to figure that your.



I fix the problem with add the "pdfjs-dist": "~2.5.207" and change the "target": "es5" inside ts.config and building the project again. This is fix my problem.
Tnks for the answer.

**Comment by VadimDez** [comment]
Fixed in version [6.4.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.0)

**Comment by dzik1331** [comment]
> Fixed in version [6.4.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.0)

Still not working. Same error with version 6.4.0

**Comment by Rahul-kalsha** [comment]
![PDFPromiseIssue](https://user-images.githubusercontent.com/56481473/111300161-c720a380-8676-11eb-85f5-41924a01b68c.png)
The above type of issue fixed in version [6.4.1](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.1)

**Comment by angelonunez2014** [comment]
> ![PDFPromiseIssue](https://user-images.githubusercontent.com/56481473/111300161-c720a380-8676-11eb-85f5-41924a01b68c.png)
> The above type of issue fixed in version [6.4.1](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.1)


For those who still encounter this issue. 

You can try installing these versions:
      "ng2-pdf-viewer": "^6.2.0",
      "@types/pdfjs-dist": "^2.1.1",
      "pdfjs-dist": "^2.3.200",

**Comment by TeemuKoivisto** [comment]
Hey people. I'm not using this library, just pdfjs-dist directly, but I fixed the types (as shown here https://github.com/mozilla/pdf.js/issues/12384#issuecomment-695138631) by importing them as following:

```ts
import type {
  PDFDocumentProxy, PDFDocumentLoadingTask
} from 'pdfjs-dist/types/display/api'
```

**Comment by matheusmurta** [comment]
For angular 7, use the fucking version "ng2-pdf-viewer": "^5.2.2" that will work very well
