### ISSUE TITLE
Doesn't compile with pdf.js 2.6 and pdf.js 2.7

### ISSUE THREAD

**Issue by stephanrauh** [VadimDez/ng2-pdf-viewer#724]
When pdfjs-dist updated to version 2.6, many classes you're using have been  removed from `types/pdf.d.ts`. As a consequence, `pdf-viewer-module.d.ts` doesn't compile. That in turn means the entire project doesn't compile.

As far as I can see, most of the offending classes have been removed or renamed entirely, so maybe compatibility to version 2.6+ is broken. I guess that's easy to fix, but it doesn't look like a no-brainer, either.

As a short-term remedy, I suggest modifying the `package.json` so it doesn't pull the latest version of pdf.js:

```json
  "dependencies": {
    "@types/pdfjs-dist": "^2.1.7",
    "pdfjs-dist": "^2.5.207<2.6",   // <<< modified line
    "tslib": "^1.10.0"
  },
```

Hint for developers using ng2-pdf-viewer: As a work-around, it suffices to install pdf.js 2.5 (`npm i -s pdfjs-dist@2.5`).

Side remark: this bug is related to, but not identical to, issue #714.

For convenience, here's the list of compiler messages I ran into:

````
Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
           ~~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:28 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
                             ~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:39 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.

5 import { PDFDocumentProxy, PDFSource, PDFProgressData } from 'pdfjs-dist';
                                        ~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:1:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.

1 import { PDFJSStatic } from 'pdfjs-dist';
           ~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:10 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFJSStatic'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
           ~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:100 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPromise'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                                                                     ~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:23 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFDocumentProxy'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                        ~~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:41 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFViewerParams'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                          ~~~~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:58 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFPageProxy'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                           ~~~~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:72 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFSource'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
                                                                         ~~~~~~~~~


Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts:7:83 - error TS2305: Module '"../../../../pdfjs-dist/types/pdf"' has no exported member 'PDFProgressData'.

7 export { PDFJSStatic, PDFDocumentProxy, PDFViewerParams, PDFPageProxy, PDFSource, PDFProgressData, PDFPromise } from 'pdfjs-dist';
```

**Comment by roszniowski** [comment]
Hi, 
For Angular 8 I had problem to set version in package.json as you wrote 

> ```json
>   "dependencies": {
>     "@types/pdfjs-dist": "^2.1.7",
>     "pdfjs-dist": "^2.5.207<2.6",   // <<< modified line
>     "tslib": "^1.10.0"
>   },
> ```

but found on stackoverflow solution to use ~2.5.207 that works properly.

> ~version “Approximately equivalent to version”, will update you to all future patch versions, without incrementing the minor version. ~1.2.3 will use releases from 1.2.3 to <1.3.0.

Thanks!

**Comment by VadimDez** [comment]
Fixed in version [6.4.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/6.4.0)

**Comment by fazizian** [comment]
Hi,

I still have the problem after updated to the last version.
Exactly the same errors as @stephanrauh 

Angular 11

```
    "ng2-pdf-viewer": "^6.4.0",
    "pdfjs-dist": "^2.6.347",
```

**Comment by VadimDez** [comment]
@fazizian don't install `pdfjs-dist` yourself, let ng2-pdf-viewer install required version.

**Comment by fazizian** [comment]
Ok, it works if I let ng2-pdf-viewer install required version.
So ng2-pdf-viewer is not compatible with the two last version of pdfjs-dist.
When do you think it will be available ?

**Comment by adamdport** [comment]
FWIW I boxed with both ng2-pdf-viewer and pdfjs-dist for hours yesterday and kept getting build issues ("no exported member"). Even completely wiping out my node-modules, clearing npm cache, upgrading, downgrading, etc wouldn't help. Finally I copied the `node_modules/@types/pdfjs-dist` folder from a coworker's machine and it's been working ever since. Doesn't give me warm fuzzies about how npm works, but I thought I'd share in case someone else is having similar issues.
