### ISSUE TITLE
ng2-pdf-viewer + angular 13

### ISSUE THREAD

**Issue by ODAncona** [VadimDez/ng2-pdf-viewer#846]
##### Bug Report or Feature Request (mark with an `x`)
```
- [X] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I'm unable to make a hello world app with angular 13 similar to [this one](https://stackblitz.com/edit/ng2-pdf-viewer). The application compile but the pdf don't show. In the dom, the src field is incomplete:

![image](https://user-images.githubusercontent.com/71207824/147690287-38f60f62-a48d-407e-a81b-29dfc7eacdff.png)

**Dependencies**
```
  "dependencies": {
    "@angular/animations": "~13.1.0",
    "@angular/common": "~13.1.0",
    "@angular/compiler": "~13.1.0",
    "@angular/core": "~13.1.0",
    "@angular/forms": "~13.1.0",
    "@angular/platform-browser": "~13.1.0",
    "@angular/platform-browser-dynamic": "~13.1.0",
    "@angular/router": "~13.1.0",
    "ng2-pdf-viewer": "^7.0.2",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
}
```

**App.ts**
```
import { Component } from '@angular/core';

@Component({
  selector: 'example-app',
  template: `
  <pdf-viewer [src]="pdfSrc"
              [render-text]="true"
              [original-size]="false"
              style="style="width: 400px; height: 500px"
  ></pdf-viewer>
  `
})
export class AppComponent {
  pdfSrc = "https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf";
}
```

**App.module.ts**
```
import { PdfViewerModule } from 'ng2-pdf-viewer';

@NgModule({
  imports: [BrowserModule, PdfViewerModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
```

**Comment by VadimDez** [comment]
You have an error in your template:
`style="style="width: 400px; height: 500px"`

**Comment by maxbalan** [comment]
@VadimDez even ignoring the template error, just by upgrading the demo project to angula 13, seems to be failing.

**Comment by maxbalan** [comment]
as a workaround for those facing the same issue, reverted back to last working version for me `^6.4.0`, seems to be working fine with angular 13.1.1

**Comment by ODAncona** [comment]
> You have an error in your template: `style="style="width: 400px; height: 500px"`

its true, I'm always fixing it when I copy it. The mistake is as well in the npm package get started.

I found the code there: https://www.npmjs.com/package/ng2-pdf-viewer

**Comment by psarno** [comment]
We are using `"ng2-pdf-viewer": "^7.0.1",` with Angular 13 without issue.

**Comment by timscriv** [comment]
We upgraded to Angular 13 and `^7.0.2` and began to see this bug. 

Tried using `7.0.1` which did not fix the issue. 

Dropped back to `^6.4.0` like @maxbalan posted, this resolved the issue. 👍

**Comment by anddam** [comment]
I am seeing this too with Angular 12.2.5 and ng2-pdf-viewer ~7.0 .

Reverting to 6.4.1 does render the PDF. I am using the [stackblitz example](https://stackblitz.com/edit/ng2-pdf-viewer) as test, with the bump on @angular/cli version that is inconsistent with the rest of the framework.

**Comment by VadimDez** [comment]
Version [8.0.0](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/8.0.0) is released, can you please test it and give a feedback if this is now fixed for you?

**Comment by kettunen** [comment]
For us this was still an issue with Angular 13 and 8.0.1. It's a css issue related to <pdf-viewer> or some element inside it. In out implementation pdf-viewer is inside <mat-card> and giving 100% height for pdf-viewer doesn't work. It shows if you give height like 500px or 100vh but either of those work for us. That's why we had to revert back to 6.4.1.

**Comment by anddam** [comment]
>In out implementation pdf-viewer is inside and giving 100% height for pdf-viewer doesn't work. It shows if you give height like 500px or 100vh but either of those work for us.

I am not sure to fully understand what you meant there, but check [this comment](https://github.com/VadimDez/ng2-pdf-viewer/issues/863#issuecomment-1047534199).

**Comment by nCr78** [comment]
Hello, can you please revert those changes (the need of height/width or absolute position to work) from 7.0.0 and after or provide additional documentation? I reverted back to 6.4.1 where it just works. Nobody wants to do CSS hacks through TS to get actual sizes. It doesn't work with plain flexbox or absolute positions when you want a certain scrolling behavior (e.g. scroll whole HTML document, and not the pdf-viewer element).

Hope this makes sense.

**Comment by VadimDez** [comment]
Dear @nCr78
No, those changes won't be reverted as they're critical to make pdfs work.
Feel free to provide a solution that doesn't require setting both width and height.

**Comment by blakeja** [comment]
This is still a problem with v9.0.0, reverting back to 6.4.0 fixed the issue with Angular 13.2.4.

**Comment by AsimNet** [comment]
show the pdf with Blob:
```
    onInit() {
            this.loading = true;
            this.downloadFile(this.content.media_file).pipe(takeUntil(this.destroyed$)).subscribe(res => {
                this.pdfUnit8Array = res;
                this.loading = false;
                this.cdr.detectChanges();
            });
    }

    private downloadFile(url: string): any {
        return this.http.get(url, { responseType: 'arraybuffer' })
            .pipe(
                map((result: any) => {
                    return new Uint8Array(result);
                })
            );
    }
```

**Comment by peterheMP** [comment]
This is still a prob with v9.1.0, reverting back to 7.0.2 fixed the issue with Angular 13.3.9.

**Comment by Sreejith-Neelakumari-Simelabs** [comment]
Node.js v18.16.0 

Getting errors  like below 

node:events:491
      throw er; // Unhandled 'error' event
      ^

 

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (D:\22022023\22052023\IM-ENT-Angular\node_modules\memfs\lib\volume.js:2030:17)
    at FsReadStream._destroy (D:\22022023\22052023\IM-ENT-Angular\node_modules\memfs\lib\volume.js:2015:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (D:\22022023\22052023\IM-ENT-Angular\node_modules\memfs\lib\volume.js:1945:22)
    at class_1.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

 

Node.js v18.16.0

**Comment by aledbout** [comment]
Look closely at this answer https://angulardev.space/questions/issues-with-displaying-all-pages-in-the-ng2-pdf-viewer
